name: mailassist

services:
  rag-microservice:
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    build: ./backend/rag-microservice
    ports:
      - "3000:3000"
    env_file:
      - .env
      - ./backend/rag-microservice/.env
    networks:
      - mailassist

  reranking-microservice:
    build: ./backend/reranking-microservice
    ports:
      - "8001:8001"
    networks:
      - mailassist

  embedding-microservice:
    build: ./backend/embedding-microservice
    ports:
      - "8002:8002"
    networks:
      - mailassist

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        VITE_BACKEND_URL_WS: ${VITE_BACKEND_URL_WS}
    ports:
      - "8080:80"
    depends_on:
      rag-microservice:
        condition: service_started
    networks:
      - mailassist

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 40
      start_period: 10s
    networks:
      - mailassist

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list | grep -q 'mistral:7b' && ollama list | grep -q 'nomic-embed-text'"]
      interval: 15s
      timeout: 10s
      retries: 40
      start_period: 600s
    networks:
      - mailassist

networks:
  mailassist:
    name: mailassist

volumes:
  pgdata:
  ollama_data:
