name: email-rag

services:
  nestja-rag:
    depends_on:
      - db
    build: ./backend/nestjs-rag
    ports:
      - "3000:3000"
  reranking-microservice:
    build: ./backend/reranking-microservice
    ports:
      - "8001:8001"

  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: email-rag
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  #ollama:
  #  image: ollama/ollama
  #  container_name: ollama-services
  #  ports:
  #    - "11434:11434"
  #  volumes:
  #    - ollama_data:/root/.ollama

volumes:
  pgdata:
  ollama_data:
