http {
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
        }
        location /api/socket.io/ {
            proxy_pass http://rag-microservice:3000
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}

events {}